repos:
  - repo: local
    hooks:
      - id: isort
        name: isort
        stages: [commit]
        language: system
        entry: pipenv run isort
        types: [python]

      - id: black
        name: black
        stages: [commit]
        language: system
        entry: pipenv run black
        types: [python]

      - id: flake8
        name: flake8
        stages: [commit]
        language: system
        entry: pipenv run flake8
        types: [python]
        exclude: setup.py

      - id: mypy
        name: mypy
        stages: [commit]
        language: system
        entry: pipenv run mypy
        types: [python]
        pass_filenames: false

      - id: bandit
        name: bandit
        stages: [ commit ]
        language: system
        entry: pipenv run bandit
        types: [ python ]
        pass_filenames: false

      - id: pytest
        name: pytest
        stages: [ commit ]
        language: system
        entry: pipenv run test
        types: [ python ]