repos:
  - repo: local
    hooks:
      - id: isort
        name: isort
        stages: [commit]
        language: system
        entry: pipenv run imports
        types: [python]

      - id: black
        name: black
        stages: [commit]
        language: system
        entry: pipenv run format
        types: [python]

      - id: flake8
        name: flake8
        stages: [commit]
        language: system
        entry: pipenv run lint
        types: [python]

      - id: mypy
        name: mypy
        stages: [commit]
        language: system
        entry: pipenv run types
        types: [python]
        pass_filenames: false

      - id: bandit
        name: bandit
        stages: [ commit ]
        language: system
        entry: pipenv run bandit-check
        types: [ python ]
        pass_filenames: false

      - id: pytest
        name: pytest
        stages: [ commit ]
        language: system
        entry: pipenv run test
        types: [ python ]
        pass_filenames: false
        always_run: true