[tool.black]
line-length = 120
target-version = ["py310", "py311"]
include = '\.pyi?$'
extend-ignore = ["E203", "B101"]

[tool.isort]
profile = "black"
multi_line_output = 3
py_version = 310

[tool.bandit]
exclude_dirs = ["src/**/tests", "deploy", "config", "settings"]
tests = ["B201", "B301"]
skips = ["B101", "B601"]

[tool.mypy]
python_version = "3.10"
ignore_missing_imports = true
disallow_untyped_defs = true
show_error_codes = true
no_implicit_optional = true
warn_return_any = true
warn_unused_ignores = true
follow_imports = 'skip'